aemsites/bsca-secondsale

group/blocks/cards/cards.css, group/blocks/cards/cards.js, group/blocks/slider/slider.css, group/blocks/slider/slider.js, group/scripts/utils.js, group/styles/styles.css
Style main, list, and secondary cards.
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/traderjoes/tj1
- After: https://three-card--bsca-secondsale--aemsites.aem.live/group/traderjoes/tj1
=> Card Style update

group/blocks/cards/cards.css, group/blocks/cards/cards.js, group/blocks/hero/hero.css, group/blocks/hero/hero.js, group/scripts/scripts.js, group/styles/styles.css
Based on customer meeting, we changed cards document format.
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/
- After: https://cards-refactor--bsca-secondsale--aemsites.aem.live/group/
=> Update cards and hero

group/blocks/cards/cards.css, group/blocks/fragment/fragment.css, group/blocks/hero/hero.css
Adjusted secondary card across screen resolutions.
Fix #28 
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/
- After: https://secondary-card--bsca-secondsale--aemsites.aem.live/group/
=> Mobile alignments

group/scripts/test.js, tools/importer/importer-landing.js, tools/importer/importer-tabs.js
Adjusted heading tags to match docs.
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/traderjoes/tj1/documents
- After: https://importer-refactor--bsca-secondsale--aemsites.aem.live/group/traderjoes/tj1/documents
=> Importer refactor

group/blocks/columns/columns.css, group/styles/styles.css
Test URLs:
- Before: https://mdc-520662-secondary-button-fix--bsca-secondsale--aemsites.aem.live/group/traderjoes/tj2
- After: https://mdc-520662-secondary-button-fix--bsca-secondsale--aemsites.aem.live/group/traderjoes/tj2
=> Mdc 520662 secondary button fix

group/blocks/chatbot/chatbot.css, group/blocks/chatbot/chatbot.js
Fix #38 
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/drafts/asha/cob
- After: https://chatbot-column--bsca-secondsale--aemsites.aem.page/group/drafts/asha/cob
=> creating 2 column for chatbot fragment

group/blocks/chatbot/chatbot.js, group/blocks/columns/columns.css, group/styles/styles.css
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/cob/cob
- After: https://mdc-520653-column-styling--bsca-secondsale--aemsites.aem.page/group/cob/cob
=> Mdc 520653 column styling

group/blocks/cards/cards.css, group/blocks/cards/cards.js
Fix #45 
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/drafts/ncsmig/pharmacy
- After: https://two-cards-layout--bsca-secondsale--aemsites.aem.page/group/drafts/ncsmig/pharmacy
=> two cards layout

group/blocks/chatbot/chatbot.css, group/blocks/chatbot/chatbot.js
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/sanmanuel/sanmanuel
- After: https://chatbot-alignment--bsca-secondsale--aemsites.aem.page/group/sanmanuel/sanmanuel
=> chatbot alignment fixes

group/blocks/columns/columns.css, group/blocks/columns/columns.js, tools/importer/importer-main.js
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/drafts/sanmanuel/sanmanuel
- After: https://column-card--bsca-secondsale--aemsites.aem.page/group/drafts/sanmanuel/sanmanuel
=> Icon card styling and importer updates

group/blocks/header/header.css, tools/importer/import-nav.js
Fix #47 
Test URLs:
- https://nav-importer--bsca-secondsale--aemsites.aem.page/group/drafts/sanmanuel/sanmanuel
=> Nav import script

group/blocks/columns/columns.css, group/blocks/header/header.css
Jira ticket mdc-523086
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/cob/
- After: https://mdc-523086--bsca-secondsale--aemsites.aem.live/group/cob/
=> Adjust columns

group/blocks/columns/columns.js
Jira ticket mdc-523084
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/cob/
- After: https://mdc-523084--bsca-secondsale--aemsites.aem.live/group/cob/
=> Add video link to video image

group/blocks/hero/hero.css
Jira ticket mdc-523083
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/cob/
- After: https://mdc-523083--bsca-secondsale--aemsites.aem.live/group/cob/
=> Adjust Hero

group/blocks/banner/banner.css, group/blocks/columns/columns.css, group/blocks/fragment/fragment.css, group/blocks/header/header.css, group/blocks/tabs/tabs.css
Fixes for:
1. margins around column block
2. border rules for fragment when it contains a list or another fragment.
3. tab label width
4. home icon width
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/drafts/ccpoa/retiree
- After: https://spacing-fixes--bsca-secondsale--aemsites.aem.page/group/drafts/ccpoa/retiree
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/cseba/
- After: https://spacing-fixes--bsca-secondsale--aemsites.aem.page/group/cseba/
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/calpers/retirees/plan-documents
- After: https://spacing-fixes--bsca-secondsale--aemsites.aem.page/group/calpers/retirees/plan-documents
=> spacing fixes

group/blocks/banner/banner.css, group/blocks/columns/columns.css, group/blocks/columns/columns.js, group/styles/styles.css
1. column align on top
2. spacing in banner
3. disclaimer margin adjustments
Test URLs:
Column alignment and disclaimer: 
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/oc/retirees-medicare
- After: https://spacing-fixes--bsca-secondsale--aemsites.aem.page/group/oc/retirees-medicare
Banner:
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/providence/
- After; https://spacing-fixes--bsca-secondsale--aemsites.aem.page/group/providence/
=> fixing spacing issues

group/blocks/columns/columns.css, group/styles/styles.css
Striped column alignment fixes
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/mcsig/
- After: https://column-alignment-fixes--bsca-secondsale--aemsites.aem.page/group/mcsig/
=> Style updates for align-top

group/blocks/chatbot/chatbot.js, group/blocks/header/header.js
1. adding title to logo. This will require authoring change as well ([nav.docx](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BC041CAD1-EE4E-4EDD-84C6-560E557C6922%7D&file=nav.docx&action=default&mobileredirect=true))
2. Title for Chatbot iframe
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.page/group/stanford/
- After: https://logo-accessibility-fix--bsca-secondsale--aemsites.aem.page/group/drafts/asha/
=> Accessibility Score Improvement

group/blocks/columns/columns.js
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/ventura/
- After: https://column-image-fix--bsca-secondsale--aemsites.aem.page/group/ventura/
=> adding target attribute to images in column

group/scripts/scheduling/scheduling.css, group/scripts/scheduling/scheduling.js, group/scripts/scripts.js
Section and block visibility
Test URLs:
- https://block-visibility-scheduler--bsca-secondsale--aemsites.aem.page/group/drafts/asha/
=> block and section visibility scheduling

group/blocks/chatbot/chatbot.js
The placeholders where not loading in time. Moved the fetch to decorate.
Test URLs:
- Before: https://main--bsca-secondsale--aemsites.aem.live/group/cob/
- After: https://chat-placeholder--bsca-secondsale--aemsites.aem.live/group/cob/
=> Chat placeholder update
